//--------------------------------------------------------------------------------
// Auto-generated by Migen (--------) & LiteX (05815c4e) on 2020-04-28 16:55:08
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#define ROM_BASE 0x00000000L
#define ROM_SIZE 0x00008000

#define SRAM_BASE 0x01000000L
#define SRAM_SIZE 0x00001000

#define CSR_BASE 0x82000000L
#define CSR_SIZE 0x00010000

#define MAIN_RAM_BASE 0x40000000L
#define MAIN_RAM_SIZE 0x10000000

#endif
