//--------------------------------------------------------------------------------
// Auto-generated by Migen (--------) & LiteX (05815c4e) on 2020-04-28 16:55:08
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 100000000
#define CONFIG_CPU_HAS_INTERRUPT
#define CONFIG_CPU_RESET_ADDR 0
#define CONFIG_CPU_TYPE_VEXRISCV
#define CONFIG_CPU_VARIANT_STANDARD
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_L2_SIZE 8192
#define DMA_CHANNELS 2
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define PCIE_DMA1_READER_INTERRUPT 2
#define PCIE_DMA1_WRITER_INTERRUPT 3
#define TIMER0_INTERRUPT 1
#define UART_INTERRUPT 0

#endif
